import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { MDBInput } from 'mdb-react-ui-kit'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className=' flex form'>
          <MDBInput label='Your Salary' className='input' type='text' />
          <MDBInput label='Your Desired Rent Cost' className='input' type='text' />
          <MDBInput label='Your Desired COL' className='input' type='text' />
        </div>
      </main>
    </>
  )
}
