import Head from 'next/head'
import styles from '@/styles/Home.module.scss'
import { MDBInput, MDBDropdown, MDBDropdownMenu, MDBDropdownToggle, MDBDropdownItem } from 'mdb-react-ui-kit'
import { useState, useEffect } from 'react'
import COLTable from './COLTable'
import {cityData} from 'cityData.js'

export default function Home() {
  const [jobTitle, setJobTitle] = useState('')
  const [currentLocation, setCurrentLocation] = useState('')
  const [livingType, setLivingType] = useState('')
  // const [citiesData, setCitiesData] = useState([])

  // useEffect(() => {
  //   fetch('/api/cities')
  //     .then(response => response.json())
  //     .then(data => {
  //       console.log(data)
  //       setCitiesData(data)
  //     })
  // }, [])

  const handleJobTitle= (e) => setJobTitle(e.target.value)

  const handleCurrentLocation= (e) => setCurrentLocation(e.target.value)

  const handleLivingType= (e) => setLivingType(e.target.textContent)

  return (
    <>
      <Head>
        <title>Hackabull 2023</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className=' flex form'>
          <MDBInput label='Job Title' className='input' type='text' value={jobTitle} onChange={e => handleJobTitle(e)} />
          <MDBInput label='Current Location' className='input' type='text' value={currentLocation} onChange={e => handleCurrentLocation(e)} />
          <MDBDropdown animation>
            <MDBDropdownToggle>{livingType || 'Living Type'}</MDBDropdownToggle>
            <MDBDropdownMenu>
              <MDBDropdownItem link onClick={e => handleLivingType(e)}>Rent</MDBDropdownItem>
              <MDBDropdownItem link onClick={e => handleLivingType(e)}>Buy</MDBDropdownItem>
              <MDBDropdownItem link onClick={e => handleLivingType(e)}>Lease</MDBDropdownItem>
            </MDBDropdownMenu>
          </MDBDropdown>
        </div>
        <div className='data'>
          <h1>Cities</h1>
          <COLTable userCity={currentLocation}/>
        </div>
      </main>
    </>
  )
}
